name: "Detect Impacted Domains"
description: "Detect which domains are impacted based on git changes"
author: "flxbl-io"

branding:
  icon: "git-branch"
  color: "purple"

inputs:
  release-config-path:
    description: "Path to directory containing release config files (glob pattern supported)"
    required: false
    default: "config/release-config-*.yaml"
  base-ref:
    description: "Base ref to compare against (e.g., origin/main, HEAD~1)"
    required: false
    default: "origin/main"
  head-ref:
    description: "Head ref to compare (default: HEAD)"
    required: false
    default: "HEAD"
  sfdx-project-path:
    description: "Path to sfdx-project.json"
    required: false
    default: "sfdx-project.json"

outputs:
  has-changes:
    description: "Whether any domains have changes (true/false)"
  impacted-domains:
    description: "JSON array of impacted domain names"
  matrix:
    description: "GitHub Actions matrix JSON for impacted domains"

runs:
  using: "node20"
  main: "dist/index.js"
